/*

 RANDOMCHAR.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char RandomChar[] =
{
  0xFE,0xFE,0x82,0x82,0xBF,0xBF,0x95,0x95,
  0x81,0x81,0x9F,0x9F,0xC2,0xC2,0x7E,0x7E
};

/* End of RANDOMCHAR.C */
